// The audience aggregate — the single seam where real registration data enters The Decision
// Room. Every downstream module (simulator, dashboards, game store) reads AUDIENCE from here
// and nothing else touches the registration CSV.
//
// GENERATED by scripts/import-audience.ts from the real registration export. Do not hand-edit the
// numbers; re-run the import against a fresh CSV instead. The survey stays open until the event,
// so this file is expected to be regenerated more than once.
//
// THE SHAPE BELOW IS THE FORM THAT WAS ACTUALLY SENT, not the one this project was first written
// against. The live form differs from docs/registration-questions.md in ways that each broke
// something:
//
//   - Queue patience thresholds are 5 / 10 / 15 / forever. The old schema floor was 3 minutes and
//     the original round-1 script was built on "you said you walk away after three minutes".
//     Nobody was ever offered three minutes.
//   - `Bus` replaced `BTS / MRT`.
//   - Two questions were ADDED — what people usually SPEND, and what actually DECIDES their
//     purchase. Those two now carry round 1 (see lib/pricing.ts); they have far more signal than
//     the five they were added to.
//   - `nothing` is no longer offered as a first drink. Kept in the type, so a zero is honest
//     and the option can return, but nobody can currently land in it.

export type AudienceAggregate = {
  respondents: number
  arrivalMode: Record<'walk' | 'bus' | 'car' | 'moto', number>
  wakeTime: Record<'before6' | '6to8' | '8to10' | 'after10', number>
  firstDrink: Record<'coffee' | 'tea' | 'water' | 'nothing', number>
  /**
   * What they BUY first, which is not what they drink first — see MOCK_FIELDS below. The form
   * asked what people drink when they wake up, and the honest answer to that is water: it is what
   * a body wants on waking, not a thing anyone chose or paid for. A question about a café has to
   * ask about the first drink someone BUYS.
   */
  firstBuy: Record<'coffee' | 'tea' | 'juice' | 'milk' | 'none', number>
  buyTime: Record<'before7' | '7to9' | '9to11' | 'after11' | 'never', number>
  /** Minutes they will stand in a queue before giving up. `any` never leaves. */
  queuePatience: Record<'under5' | 'under10' | 'under15' | 'any', number>
  /**
   * What they say they usually pay for a drink, ฿. Round 1 reads the TOP of each band as that
   * person's ceiling, which is what puts the profit optimum where it is — see lib/pricing.ts.
   */
  spend: Record<'under50' | '50to100' | '101to200', number>
  /**
   * What decides the purchase. MULTI-SELECT: these DO NOT sum to `respondents` (here they sum
   * to 128 across 50 people), and `bucketTotal` must never be
   * asserted against this field. content/audience.test.ts exempts it by name rather than relaxing
   * the check for the others.
   *
   * This is the column that answers "why would cutting the price not work?" — it is deliberately
   * NOT a term in the round-1 simulation, where a coefficient would bury it. It is evidence on
   * the outcome screen, explaining the volume that did not move.
   */
  mainFactor: Record<'taste' | 'price' | 'brand' | 'promotion' | 'convenience', number>
}

/** Single-choice fields, which must sum to `respondents`. `mainFactor` is deliberately absent. */
export const SINGLE_CHOICE_FIELDS = [
  'arrivalMode', 'wakeTime', 'firstDrink', 'firstBuy', 'buyTime', 'queuePatience', 'spend',
] as const

/**
 * Distributions with NO COLUMN BEHIND THEM YET.
 *
 * Everything else in this file is a real answer (scaled — see the note below). `firstBuy` is not:
 * the question has not been asked yet, and these numbers are a plausible stand-in written so the
 * café's partnership round has a chart that bears on the decision at all.
 *
 * IT IS MARKED ON SCREEN. `components/room/Stages.tsx` prints "ข้อมูลตัวอย่าง" in the chart's meta
 * line for anything named here, because the whole premise of this workshop is that the room is
 * looking at ITS OWN data — telling them a made-up bar is theirs is the one lie this deck cannot
 * afford, and it is the exact move the other workshop spends nine minutes teaching them to catch.
 *
 * TO RETIRE IT: add the column to the registration form, and `scripts/import-audience.ts` already
 * knows how to read it (HEADER_KEYS.firstBuy). Delete the name from this set on the same commit
 * that lands the real numbers.
 */
export const MOCK_FIELDS: ReadonlySet<string> = new Set(['firstBuy'])

// Real registration data has been imported — the placeholder badge is off.
export const IS_PLACEHOLDER = false

// MOCK SCALE-UP (event-scale preview): the real export had N=18; every bucket below is that
// distribution multiplied by 50/18 and rounded so single-choice fields sum to 50. The survey is
// open until the event — re-run scripts/import-audience.ts against the final CSV to replace this
// with real numbers before the day.
export const AUDIENCE: AudienceAggregate = {
  "respondents": 50,
  "arrivalMode": {
    "walk": 3,
    "bus": 3,
    "car": 41,
    "moto": 3
  },
  "wakeTime": {
    "before6": 14,
    "6to8": 25,
    "8to10": 8,
    "after10": 3
  },
  "firstDrink": {
    "coffee": 17,
    "tea": 11,
    "water": 22,
    "nothing": 0
  },
  "firstBuy": {
    "coffee": 21,
    "tea": 9,
    "juice": 6,
    "milk": 3,
    "none": 11
  },
  "buyTime": {
    "before7": 3,
    "7to9": 22,
    "9to11": 6,
    "after11": 8,
    "never": 11
  },
  "queuePatience": {
    "under5": 11,
    "under10": 22,
    "under15": 9,
    "any": 8
  },
  "spend": {
    "under50": 3,
    "50to100": 36,
    "101to200": 11
  },
  "mainFactor": {
    "taste": 50,
    "price": 31,
    "brand": 8,
    "promotion": 22,
    "convenience": 17
  }
}

export function bucketTotal(rec: Record<string, number>): number {
  return Object.values(rec).reduce((sum, v) => sum + v, 0)
}
